version: "3.8"

services:
 php:
  build:
   context: ./docker
  volumes:
   - .:/var/www/html
  links:
   - mysql
  command: sh -c "cp .env.example .env && php-fpm"
  environment:
   - MYSQL_HOST=mysql
   - MYSQL_DATABASE=test
   - MYSQL_ROOT_PASSWORD=root_car
   - MYSQL_USER=root
   - MYSQL_PASSWORD=root

 mysql:
  image: mysql:8.0
  ports:
   - "3316:3306"
  volumes:
   - mysql-data:/var/lib/mysql
  environment:
   - MYSQL_DATABASE=test
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_USER=root
   - MYSQL_PASSWORD=root

 nginx:
  image: nginx:latest
  volumes:
   - ./docker/default.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8080:80"
  links:
   - php

volumes:
 mysql-data:
