user www www;
worker_processes 2;
pid /var/run/nginx.pid;

error_log /var/log/nginx.error_log info;

events {
    worker_connections 2000;
}

http {
    include mime.types;
    default_type application/octet-stream;

    log_format main
        '$remote_addr - $remote_user [$time_local] '
        '"$request" $status $bytes_sent '
        '"$http_referer" "$http_user_agent" '
        '"$gzip_ratio"';

    sendfile on;

    server {
        listen 80;
        server_name example.com www.example.com;
        access_log /var/log/nginx.access_log main;

        root /path/to/public; # Aquí se especifica la ruta a la carpeta public

        location / {
            index index.php index.html index.htm;
        }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
    }
}